[versions]
agp = "8.3.2"
appcompat = "1.7.1"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

